### ISSUE TITLE
DLRN/TripleO CI integration tests

### ISSUE THREAD

**Issue by yac** [softwarefactory-project/rdopkg#135]
As `DLRN` is one of main `rdopkg` consumers, `rdopkg` gate should include `DLRN` integration tests.

**Comment by javierpena** [comment]
If we wanted to reuse the same jobs used by DLRN, we need a few things:

- https://softwarefactory-project.io/r/9334 (already merged) fixed the way DLRN was cloned, so that is already there.
- We need a way to use zuul-cloner to get rdopkg and install it in the virtual environment. This is a bit tricky, we have done it for rdoinfo [1], but that only works in the DLRN-rpmbuild job.
- Other jobs do not call run_tests.sh (for example the TripleO-related ones), so maybe a better alternative is to inject that rdopkg clone directly in the jobs.
- Maybe a better idea would be to create an rdopkg-specific job, mostly based on the current DLRN ones but separate. That would fix the case where DLRN is pinning rdopkg to a specific version, and its CI would be broken with the current master.

[1] - https://github.com/softwarefactory-project/DLRN/blob/master/scripts/run_tests.sh#L30-L36

**Comment by yac** [comment]
DLRN integration tests were added.
