### ISSUE TITLE
RFE: properly support various distroinfo repos

### ISSUE THREAD

**Issue by yac** [softwarefactory-project/rdopkg#167]
Make all rdopkg actions that use rdoinfo reusable on other *info instances as well. 

There was a first attempt to do this for `rdopkg clone` in a6e6497 which introduces `--distro` param to config distroinfo repos in rdopkg config, but it needs more thorough and native support.

Currently rdopkg supports `-l`/`--local-info` parameter to select info repo but info_file is hardcoded to `rdo-full.yml`. That leaves us wit following options:

a) just add `-L`/`--info-files` parameter to select info_files too (path of least resistance)
b) refactor to fully support passing distroinfo params to info actions (INFO_URL, INFO_FILES)
c) use suggested `-d`/`--distro` attribute and have relevant distroinfo config in rdopkg config

and it would probably be best to do both b) and c)

**Comment by javierpena** [comment]
I still like option a), since it would keep compatibility with existing users, and just require a minimum change to support info_files. While at it, I think we could extend support for --local-info to other subcommands.

On the other hand, a refactor is also a good idea, but more invasive (and longer term).

**Comment by yac** [comment]
OK, I implemented a) alongside non-intrusive refactor which allows for b) and c) in the future if desired.

https://softwarefactory-project.io/r/c/15239/
